dist: trusty

language: java

jdk:
  - oraclejdk11

notifications:
  email:
      - notification@google.com

install: /bin/true

script:
  - mvn clean
  - mvn install

cache:
  directories:
  - $HOME/.m2
  